### ISSUE TITLE
질문을 보낸 후에 화면 초기화 할 경우

### ISSUE THREAD

**Issue by Dhani5703** [bonggongii/bonggongiiBot#20]
메세지 리스트 다 지워지긴 하지만, 몇초 뒤 아까 물어본(삭제한) 질문에 대한 응답이 나옵니다..!
초기화하면서 응답도 끊는 방법도 알아보고 추가해야 합니닷!

![스크린샷 2024-11-06 142344](https://github.com/user-attachments/assets/33e9719e-e2ee-4959-aeb4-8fdcd33b3a38)
질문하고 응답이 도착하기 전 대화 초기화를 누르면
![스크린샷 2024-11-06 142405](https://github.com/user-attachments/assets/8e6bdc46-fbe8-47d8-9a8e-4247f922ef72)
빈 채팅창에 아까의 질문에 대한 응답이 오는 모습

**Comment by HJunng** [comment]
#21 로 해결 완료~! 🫡

**Comment by HJunng** [comment]
#21 로 해결완료~! 🫡
